version: '2'

volumes:
  graylog.data.elastic:
    driver: "local"
  graylog.data.mongo:
    driver: "local"

services:
  mongodb:
    image: mongo:3
    container_name: mongodb
    environment:
      - TZ=Europe/Warsaw
    volumes:
      - graylog.data.mongo:/data/db

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.1
    container_name: elasticsearch
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - graylog.data.elastic:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
  graylog:
    image: graylog/graylog:3.0
    container_name: graylog
    environment:
      - GRAYLOG_PASSWORD_SECRET=mfyz11sanane22banane
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://192.168.0.1:9000/
      - GRAYLOG_WEB_ENDPOINT_URI=http://192.168.0.1:9000/api
    volumes:
      - ./GeoLite2-City.mmdb:/etc/graylog/server/GeoLite2-City.mmdb
      - ./GeoLite2-Country.mmdb://etc/graylog/server/GeoLite2-Country.mmdb
    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      - 9000:9000 # Graylog web interface and REST API
      - 5555:5555 # Raw/Plaintext TCP
      - 1514:1514 # Syslog TCP
      - 1514:1514/udp # Syslog UDP
      - 2055:2055/udp # NetFlow
      - 12201:12201 # GELF TCP
      - 12201:12201/udp # GELF UDP
